### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by shaman7036** [Konders/Petya.a_killswitch#1]
разве в hosts можно писать ip как имя домена? 
разве в hosts можно писать url с именем файла?
ещё рекомендуют выполнить net stop winmgmt

**Comment by Konders** [comment]
1. Да
2. Думаю да, на всякий случай добавлю url домена 
3.Учту, спасибо

**Comment by shaman7036** [comment]
да не правильно это он используется при резольвинге доменов и URL ему пофиг а темболее ip

**Comment by Konders** [comment]
С чего ты взял?
Даже сам только что проверил, правильно всё.
